import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Flag, Mail, ExternalLink, AlertTriangle } from "lucide-react";
import type { VideoAnalysis } from "@shared/schema";

interface CybercrimeReportProps {
  analysis: VideoAnalysis;
}

export function CybercrimeReport({ analysis }: CybercrimeReportProps) {
  const handleReportClick = () => {
    const subject = encodeURIComponent(`Deepfake Video Report - ${analysis.fileName}`);
    const body = encodeURIComponent(`
DEEPFAKE VIDEO DETECTION REPORT
================================

Video Information:
- File Name: ${analysis.fileName}
- File Size: ${(analysis.fileSize / 1024 / 1024).toFixed(2)} MB
- Resolution: ${analysis.resolution}
- Duration: ${Math.floor(analysis.duration! / 60)}:${String(analysis.duration! % 60).padStart(2, '0')}
- Frame Rate: ${analysis.frameRate} FPS

Detection Results:
- Verdict: ${analysis.isAuthentic ? 'AUTHENTIC' : 'DEEPFAKE DETECTED'}
- Confidence Score: ${analysis.confidenceScore}%
- Spatial Analysis Score: ${analysis.spatialScore}%
- Temporal Analysis Score: ${analysis.temporalScore}%

Technical Metrics:
- Face Manipulation Score: ${analysis.faceManipulationScore}%
- Audio-Visual Sync: ${analysis.audioVisualSyncScore}%
- Compression Artifacts: ${analysis.compressionArtifactsScore}%

Analysis Method:
Dual-stream architecture with CNN backbones (DenseNet, 3D CNN) and long-distance self-attention mechanism for detecting subtle inconsistencies across non-consecutive frames.

---
This report was generated by our AI-powered deepfake detection system.
Please provide additional context about where this video was found and its potential impact.
    `.trim());

    window.location.href = `mailto:cybercrime@authorities.gov?subject=${subject}&body=${body}`;
  };

  if (analysis.isAuthentic) {
    return (
      <section className="py-16 bg-card/30">
        <div className="max-w-6xl mx-auto px-4">
          <Card className="border-[hsl(160,84%,39%)]/30">
            <CardContent className="p-8 text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[hsl(160,84%,39%)]/10 mb-4">
                <Flag className="w-8 h-8 text-[hsl(160,84%,39%)]" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Video Appears Authentic</h3>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Our analysis indicates this video has not been manipulated. If you have concerns about this content, 
                you can still report it to the appropriate authorities.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>
    );
  }

  return (
    <section className="py-16 bg-destructive/5">
      <div className="max-w-6xl mx-auto px-4">
        <Card className="border-2 border-destructive/30">
          <CardHeader>
            <CardTitle className="flex items-center gap-3 text-destructive text-2xl">
              <AlertTriangle className="w-7 h-7" />
              Deepfake Detected - Report to Authorities
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="prose prose-sm max-w-none">
              <p className="text-muted-foreground leading-relaxed">
                Our analysis has identified this video as a potential deepfake. Synthetic media can be used for 
                misinformation, fraud, or harassment. If you believe this content is being used maliciously, 
                we encourage you to report it to the appropriate cybercrime authorities.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={handleReportClick}
                className="flex-1 sm:flex-none inline-flex items-center justify-center gap-2 px-6 h-12 rounded-md bg-destructive text-destructive-foreground font-semibold hover-elevate active-elevate-2 shadow-lg"
                data-testid="button-report-authorities"
              >
                <Mail className="w-5 h-5" />
                Report to Authorities
              </button>
              <p className="text-sm text-muted-foreground self-center">
                Opens pre-filled email with detection evidence
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-4 pt-4 border-t">
              <div className="space-y-2">
                <h4 className="text-sm font-semibold">Reporting Resources</h4>
                <ul className="space-y-1 text-sm">
                  <li>
                    <a 
                      href="https://www.ic3.gov" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-primary hover:underline inline-flex items-center gap-1"
                    >
                      FBI Internet Crime Complaint Center (IC3)
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </li>
                  <li>
                    <a 
                      href="https://www.justice.gov/criminal-ccips" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-primary hover:underline inline-flex items-center gap-1"
                    >
                      DOJ Computer Crime Section
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </li>
                </ul>
              </div>

              <div className="space-y-2">
                <h4 className="text-sm font-semibold">Important Information</h4>
                <p className="text-sm text-muted-foreground">
                  When reporting, include the detection report, source of the video, and any relevant context 
                  about how it's being used or distributed.
                </p>
              </div>
            </div>

            <div className="rounded-lg bg-muted/50 p-4 text-sm text-muted-foreground">
              <p className="font-medium mb-1">Disclaimer</p>
              <p>
                This analysis is provided as a tool to assist in identifying potential deepfakes. 
                Final determination should be made by qualified forensic experts and legal authorities.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
